### ISSUE TITLE
Error handler throws Exception for notices

### ISSUE THREAD

**Issue by abel-sch** [roots/acorn#113]
* [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Similar to other issues with the error handler:
the Error handler is too strict on throwing exceptions, returning the Whoops page as a response breaks many plugins' functionalities.

## Steps to reproduce

1. Cause 'Undefined Index' notice
2. Get Error-page

**Expected behavior:**
Notice should be sent but code should not be interrupted

**Actual behavior:**
A Whoops-error page is returned and code is exited

**Reproduces how often:**
100%

## Versions
2.0.0.alpha

**Comment by QWp6t** [comment]
This is intentional.

By default, deprecation errors won't throw exceptions, but every other type of error will.

If you want to suppress throwing `ErrorException`, use the [`acorn/throw_error_exception` filter](https://github.com/roots/acorn/blob/next/src/Roots/Acorn/Bootstrap/HandleExceptions.php#L54) on the `next` branch.
```php
add_filter('acorn/throw_error_exception', '__return_false');
```

We will be tagging another beta release shortly. In the meantime, feel free to switch to the `next` branch.
```sh
composer require roots/acorn dev-next
```
