### ISSUE TITLE
New Roots/Acorn (Main/beta.2) breaks on Bootloader in combination with sage 10

### ISSUE THREAD

**Issue by doit-jochem** [roots/acorn#137]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x] This request isn't a duplicate of an existing issue
* [ x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

For the Sage 10 project we wanted to disable the escalation of notices to errors because some plugins still have notices. There is a fix implemented that works in the main branch of roots/acorn.

https://github.com/roots/acorn/issues/100

When using the roots/acorn main branch, the error handler is working as expected again but the system gets a fatal error in the Bootloader.php. 

When loading the app (Line 203, $app = $this->appClassName::getInstance();) the appClassName is Application but the Illuminate/Container is loaded. The next line is setBasePath but the Container does not contain this function. 

When rewriting this line (For testing) to $app = new \Roots\Acorn\Application; the application works as expected. 

Could you tell me what went wrong here? We would like to use the most recent version so we can change the behaviour of the Error handler.

I added a few screenshots of my changes and the information xDebug is giving me.  

Hope to hear from you soon. 

With kind regards,

Jochem

## Steps to reproduce

1. Checkout the sage 10 main branch
2. run a composer require in the sage 10 folder on dev-main of the roots/acorn to update the roots/acorn package.
3. Try to run any action in the installation

**Expected behavior:** 

The line: $app = $this->appClassName::getInstance(); should get the instance of the appClassName. Not the container.

**Actual behavior:** 

The line: $app = $this->appClassName::getInstance(); Got the Container class that does not have the function setBasePath.

**Reproduces how often:** 

Every time. 

## Versions
Sage --> main branch
Roots/Acorn --> from beta to main branch. Alpha does not contain this error and has different code for getting the application:
$app = new $this->appClassName($basePath, $this->usePaths());

## Additional information
![Different code in Alpha branch](https://user-images.githubusercontent.com/69298309/141463561-cbc527db-5b4d-466e-ab84-a002698deab2.png)
![Found class in alpha branch](https://user-images.githubusercontent.com/69298309/141463564-f42225ae-4319-46da-ae19-00e32aa1f937.png)
![Found class in main branch](https://user-images.githubusercontent.com/69298309/141463566-7a3e3688-ff0e-4f12-8851-5d280022e3ab.png)
![Value of appClassName in main branch](https://user-images.githubusercontent.com/69298309/141463570-03ccdcc2-7f9f-4a4f-bb38-48bb2edc731d.png)
![Testing fix main branch](https://user-images.githubusercontent.com/69298309/141463571-2c17f3cd-746c-4753-9840-8751c2cf3a79.png)

**Comment by QWp6t** [comment]
Since `Application` extends `Container`, they share the same `public static $instance`. It sounds like at some point in your code prior to calling the `Bootloader`, something is accessing the `Container` class directly and setting the instance.

I'll work on a fix for this, but it's possible that whatever you have in there that's expecting that Container instance might be very upset when I overwrite that instance.

**Comment by QWp6t** [comment]
For now, you can call `Application::setInstance()` (you don't have to pass anything to it) prior to running the bootloader.

**Comment by doit-jochem** [comment]
Hi @QWp6t ,

I will check if the code if something is accessing the container prior before calling the bootloader. Especially if this can break with the fix. 

Thanks in advance. 

With kind regards,

Jochem

**Comment by benpsnyder** [comment]
Facing this issue as well.

**Comment by QWp6t** [comment]
This isn't something that I can address _directly_ in Acorn, but I can offer an _indirect_ workaround.

If Acorn and another plugin are fighting for a conflicting namespace, there will always be the potential that things will crash and burn. I will say that Acorn will probably always be using a newer version of Laravel components than other plugins, so if in doubt, use Acorn's application container wherever possible.

As long as conflicting plugins don't go out of their way to flush or otherwise reset the container, then booting Acorn before a conflicting plugin loads should be a viable workaround. There's an acorn:dump-bootloader (#173) command in the pipeline that should assist with booting Acorn early. This will hopefully avoid most issues.

An alternative approach is to pass an Application instance to Bootloader, i.e., `Bootloader::getInstance($app)` where `$app` is the Application instance provided by the conflicting plugin. I can sympathize with this not being an ideal solution, but again, we're talking about namespace collisions here.

In the future we _might_ offer an alternative version of Acorn that vendors and versions the entire Illuminate namespace, but such a version of Acorn would have its own set of problems.
