### ISSUE TITLE
Wrong namespace for aliases in Application::registerCoreContainerAliases()

### ISSUE THREAD

**Issue by stefanfisk** [roots/acorn#142]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

There's a couple of aliases with incorrect namespace in
https://github.com/roots/acorn/blob/9af5ffff189abd09436d4280df13c620675252a3/src/Roots/Acorn/Application.php#L274

Even when fixing them I was not able to make inject `Illuminate\Filesystem\Filesystem` after boot, but I didn't have time to debug that now.

**Comment by QWp6t** [comment]
Yeah, my bad. I'm not sure at which point that got screwed up, but it should be resolved now.

Feel free to check out #143 if you need this right away, otherwise I'll review it more thoroughly in a couple days and get it merged and tagged.

I added a test in there as well to confirm it's working so I'm pretty sure everything's fine.
