### ISSUE TITLE
Bug: Upgrading from v2.0.0-beta.8 to 2.0.0+ throws errors when WP_DEBUG is false

### ISSUE THREAD

**Issue by Swennet** [roots/acorn#242]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
After updating Acorn from v2.0.0-beta.8 to v2.1.1, having WP_DEBUG or WP_DEBUG_DISPLAY set to false in my Bedrock environment causes PHP to throw an error.

`PHP message: PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/projects/myproject/vendor/illuminate/container/Container.php:1089`

#### Temporary workarounds
Downgrading back to v2.0.0-beta.8.

### Steps To Reproduce

1. Disable either WP_DEBUG or WP_DEBUG_DISPLAY in your Bedrock environment config.
2. Try loading a page on your site.

### Expected Behavior

Errors should simply not be shown when WP_DEBUG is false, as it does in v2.0.0-beta.8.

### Actual Behavior

PHP throws an error:

```PHP message: PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/projects/myproject/vendor/illuminate/container/Container.php:1089```

### Versions

2.1.1

**Comment by retlehs** [comment]
please use https://discourse.roots.io/ for support

**Comment by ChristophHaaks** [comment]
Hi Guys :)
we encountered the same issue using Version 2.1.2. and tried to track the issue down.

In Container.php:1089 the error is thrown, because  $concrete is "Illuminate\Contracts\Debug\ExceptionHandler", which is located here : "/vendor/illuminate/contracts/Debug/ExceptionHandler.php". 
As "Illuminate\Contracts\Debug\ExceptionHandler" is only an interface its not instantiable and thus the error is correct.

This is caused by "/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php:629"
`app(ExceptionHandler::class)->report($exception);`
which uses 
`use Illuminate\Contracts\Debug\ExceptionHandler;`

The reason, why its different with debug set to on/off is here : 
/vendor/roots/acorn/src/Roots/Acorn/Bootstrap/HandleExceptions.php

`public function bootstrap(Application $app)
    {
        self::$reservedMemory = str_repeat('x', 32768);

        $this->app = $app;

        if (!$this->isDebug() || $this->hasHandler()) {
            return;
        }

        $this->app->singleton(
            \Illuminate\Contracts\Debug\ExceptionHandler::class,
            \Roots\Acorn\Exceptions\Handler::class
        );

        set_error_handler([$this, 'handleError']);
        set_exception_handler([$this, 'handleException']);
        register_shutdown_function([$this, 'handleShutdown']);
    }`

we adjusted the code to check later for isDebug :

`public function bootstrap(Application $app)
    {
        self::$reservedMemory = str_repeat('x', 32768);

        $this->app = $app;

         $this->app->singleton(
            \Illuminate\Contracts\Debug\ExceptionHandler::class,
            \Roots\Acorn\Exceptions\Handler::class
        );

        if (!$this->isDebug() || $this->hasHandler()) {
            return;
        }
        set_error_handler([$this, 'handleError']);
        set_exception_handler([$this, 'handleException']);
        register_shutdown_function([$this, 'handleShutdown']);
    }`


For us it solved the problem, but i am not sure if this is the best way to fix the issue.
Maybe adjusting the "use" in "helpers.php" might be a better solution.

**Comment by Swennet** [comment]
@retlehs 

Seems like I'm not the only one with this issue, and according to @ChristophHaaks, this is seemingly a bug in Acorn. Could you reconsider opening this issue?

**Comment by retlehs** [comment]
@Swennet Someone will need to provide the exact steps required to reproduce this bug and I'll be glad to re-open it once we've confirmed there's a bug. Following the steps you reported:

On a a site with Acorn v2.1.2, I modified my Bedrock development config:

```php
Config::define('WP_DEBUG', false);
Config::define('WP_DEBUG_DISPLAY', false);
```

Then I hit several pages on the site and there are no errors.

What do I need to do to reproduce this?

**Comment by trovster** [comment]
I get the exact same issue. Using non-development environment configuration, or with `Config::define('WP_DEBUG', false);` and/or `Config::define('WP_DEBUG_DISPLAY', false);` set, the same error discussed above is thrown. I am running **Acorn 2.1.2 (Laravel 8.83.17)**.

```
./vendor/bin/wp acorn                                                                                                                                                                                     
Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/trovster/Sites/manageminds/web/app/themes/manageminds/vendor/illuminate/container/Container.php:1089
```

**Comment by retlehs** [comment]
There are still not steps provided in this issue that I'm able to reproduce by following. 

Please push up a git repo where this issue can be reproduced consistently.

**Comment by Swennet** [comment]
@retlehs The project I experienced this issue in is a modified Bedrock + Sage application, so that might have something to do with it. I will see if I can debug or maybe reproduce this issue in a fresh install over the next two weeks.

**Comment by retlehs** [comment]
One of the first steps I do when trying to reproduce a reported bug is to spin up a fresh install.

In the future, please don't report bugs without a reduced test case that can be easily reproduced. We have no insight whatsoever into the changes that you've made that would be causing this.

At this point, this is not considered a bug. Like I said earlier, we would be glad to re-open this issue if someone provides the actual steps required to reproduce it.

**Comment by eriteric** [comment]
This post on the roots discourse has the information you need to debug these errors (starting at "Bonus"): https://discourse.roots.io/t/critical-error-when-disabling-wp-debug-in-roots-sage-10/23038/14?u=erit

So I think that this could be duplicated like so:

- Fresh clone of sage
- Set WP_DEBUG to false
- Add files to app/ directory (e.g. with acf-builder)
- Introduce a minor syntax error in the app directory
- This should then produce a critical error on the site that would otherwise go undetected when WP_DEBUG was set to true

**Comment by retlehs** [comment]
@eriteric Just followed your steps and I'm unable to reproduce. Please provide us with a git repo that contains this issue that I can pull down to reproduce.

**Comment by eriteric** [comment]
@retlehs Ok, sorry about that, will do a repo this weekend.

**Comment by code418** [comment]
For those who are still stuck with this I found a fix. I edit the app/Providers/ThemeServiceProvider.php file as follows:

```
<?php

namespace App\Providers;

use Roots\Acorn\ServiceProvider;

class ThemeServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton(
            \Illuminate\Contracts\Debug\ExceptionHandler::class,
            \Roots\Acorn\Exceptions\Handler::class
        );
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {


    }
}
```

This ensures Illuminate\Contracts\Debug\ExceptionHandler is instantiable even when WP_DEBUG is set to false.
