### ISSUE TITLE
Removing a provider breaks Acorn until removing the packages cache

### ISSUE THREAD

**Issue by retlehs** [roots/acorn#270]
Adding and then removing a service provider breaks Acorn until the packages cache is removed:

1. `composer require spatie/laravel-ignition`
2. `wp acorn package:discover`
3. `composer remove spatie/laravel-ignition`

Error:

```
In Application.php line 354:

  Skipping provider [Spatie\LaravelIgnition\IgnitionServiceProvider] because it does not exist.
```

Workaround:

1. `rm cache/acorn/framework/cache/packages.php`
2. `wp acorn optimize`

**Comment by yCodeTech** [comment]
Can we get this fixed ASAP please. I'm pretty sure `wp acorn optimize:clear` should remove all files in the cache including the packages.php and services.php. This needs resolving.

**Comment by dsturm** [comment]
Hej @yCodeTech, please feel free to open a PR on this, so one can review it.

**Comment by yCodeTech** [comment]
@dsturm I'm not skilled in this type of development, so I can not fix it and submit a pr.

**Comment by chrillep** [comment]
did some digging and laravels default method is not invoking a new php instance of the command via cli. Its removing the cache files in the same instance.

https://github.com/laravel/framework/blob/e217dca49e20cd2840970f8d307c8392012bc5be/src/Illuminate/Foundation/ComposerScripts.php#L48-L69

While acorn is initiating new php instances of wp acorn cli command. It fails returning exit code 1. Since the Provider may have been removed when executing. 

https://github.com/roots/acorn/blob/b020038947cd429d6020fc0bbc24568ffd9677d1/src/Roots/Acorn/ComposerScripts.php#L21

https://github.com/roots/acorn/blob/b020038947cd429d6020fc0bbc24568ffd9677d1/src/Roots/Acorn/Console/Console.php#L9-L17

https://github.com/roots/acorn/blob/b020038947cd429d6020fc0bbc24568ffd9677d1/src/Roots/Acorn/Console/Console.php#L99-L110

Possible solution. 
Reuse same console instance when used in clearCompiled context.

Or

reuse laravels method and make sure 

getCachedConfigPath() resolves to
`{projectpath}/storage/framework/cache/config.php`

$laravel->getCachedServicesPath() resolves to
`{projectpath}/storage/framework/cache/services.php`

$laravel->getCachedPackagesPath() resolves to
`{projectPath}/storage/framework/cache/packages.php`

instead of
`{projectpath}/bootstrap/cache/config.php`
`{projectpath}/bootstrap/cache/services.php`
`{projectPath}/bootstrap/cache/packages.php`
