### ISSUE TITLE
Bug: Routes incompatible with ValidationException

### ISSUE THREAD

**Issue by retlehs** [roots/acorn#288]
Acorn's route handling is incompatible with `ValidationException` because it throws a `422`

https://github.com/roots/acorn/blob/79eb9b02b59f7965d3cc227209dd9edf8e8058f4/src/Roots/Acorn/Bootloader.php#L230-L232

### Steps To Reproduce

1. Enable Acorn's routing
1. Add a route that will return a `422`:

```php
Route::get('/foo', function () {
    try {
        throw new \Illuminate\Validation\ValidationException(
            validator(data: [])
        );
    } catch (\Illuminate\Validation\ValidationException $exception) {
        return response()->json(data: [
            'message' => $exception->getMessage(),
            'errors' => $exception->errors(),
        ], status: $exception->status); // if you change status code to 200, it will work. Otherwise, it will be handled by WordPress
    }
});
```

h/t @thebezzo

**Comment by oskar-koli** [comment]
I'm also hitting hitting this problem when trying to return a "400 Bad Request" from a route.
Is there any reason this can't just be fixed by removing the server error and status code check from the Bootloader and just letting the response be rendered like any other? Seems somewhat nonsensical to ignore some types of responses like this.

I'd be up for doing a PR for this, if there are no objections

**Comment by Log1x** [comment]
Feel free to test and push up a PR!
