### ISSUE TITLE
view()->makeLoader() doesn't pass the variables/data

### ISSUE THREAD

**Issue by danlapteacru** [roots/acorn#69]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Hello,

I have tried to pass some variables with `view($file, $variables)->makeLoader();`, but for some reason, variables are not available in `$file`.

## Steps to reproduce

`view($file, $variables)->makeLoader();`

## Versions

Bedrock with Sage 10.

**Comment by QWp6t** [comment]
`makeLoader()` generates a php file. We don't serialize the data because presumably the data passed to the view is dynamic. Instead, generate the php file and then `include` it.

The main purpose of the function is to allow you to side-load blade views into hooks that expect a file to be returned but where you may not have access to the included data.

In some plugin, it might have something like:
```php
$some_data = []; // this is contained in a plugin that provides no hooks for you to access it

$file = apply_filters('some-plugin/template-file', $file);
include $file;
```

You can use `makeLoader()` in your theme or another plugin like this:
```php
add_filter('my-plugin/template-file', function () {
    // we assume you have this view in resources/views/vendor/some-plugin/template.blade.php
    // inside the view, you can access $some_data, which is passed by the plugin
    return view('vendor.some-plugin.template')->makeLoader();
});
```
Use view composers if you need to include some of your own data.

The reason it's done this way is because, in the example above, if you were to return `vendor/some-plugin/template.blade.php`, the plugin wouldn't render the blade view correctly, and if you were to return the compiled blade file (`getCompiled()`), the compiled blade file wouldn't have `$__env` and other blade-specific variables set. `makeLoader()` is a workaround for these scenarios.

Feel free to check out our [community discourse](https://discourse.roots.io/) if you need further support.

**Comment by codepuncher** [comment]
Thanks for that @QWp6t, it's appreciated.

For those that stumble upon this issue, here's an example of using the suggestion above of a View Composer in a package.

```php
# SageFLBuilderServiceProvider.php
<?php

declare(strict_types=1);

namespace Itineris\SageFLBuilder;

use Illuminate\Support\Facades\View;
use Itineris\SageFLBuilder\View\Composers\FLBuilder;
use Roots\Acorn\ServiceProvider;

use function Roots\base_path;

class SageFLBuilderServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(): void
    {
        $this->loadViewsFrom(
            base_path('app/Plugins/FLBuilder/Modules/'),
            'Sage'
        );

        $this->loadViewsFrom(
            __DIR__ . '/../resources/views/',
            'ItinerisSageFLBuilder'
        );

        View::composer(FLBuilder::views(), FLBuilder::class);
    }
}
```
With `View::composer(FLBuilder::views(), FLBuilder::class);` we reference the array of views that are defined in the Composer `FLBuilder::views()`.

```php
# Views/Composers/FLBuilder.php
<?php

declare(strict_types=1);

namespace Itineris\SageFLBuilder\View\Composers;

use FLBuilderModel;
use FLThemeBuilderLayoutData;
use Roots\Acorn\View\Composer;

class FLBuilder extends Composer
{
    /**
     * List of views served by this composer.
     *
     * @var array
     */
    protected static $views = [
        'fl-builder-archive',
        'fl-builder-single',
        'ItinerisSageFLBuilder::fl-builder-archive',
        'ItinerisSageFLBuilder::fl-builder-single',
    ];

    protected function getPostId(): int
    {
        $ids = FLThemeBuilderLayoutData::get_current_page_content_ids();

        if ('fl-theme-layout' === get_post_type() && count($ids) > 1) {
            return $post_id = FLBuilderModel::get_post_id();
        }

        return $ids[0] ?? get_the_ID();
    }

    /**
     * Data to be passed to view before rendering.
     *
     * @return array
     */
    public function with(): array
    {
        return [
            'post_id' => $this->getPostId(),
        ];
    }
}
```

Notice that the views array includes non-namespaced (for the theme) and namespaced (from the package) views.
